name: Build-And-Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout NBAProject.Blazor repository
        id: checkout
        uses: actions/checkout@v2
      
      - name: Variable Substitution for appsettings.json
        uses: microsoft/variable-substitution@v1
        with:
          files: '**/appsettings*.json'
        env:
          ApiSettings.BaseUrl: ${{ secrets.API_BASE_URL }}
          ApiSettings.ApiUsername: ${{ secrets.API_USERNAME }}
          ApiSettings.ApiPassword: ${{ secrets.API_PASSWORD }}
       
      - name: Execute build script (Debug)
        id: build_debug
        if: github.ref != 'refs/heads/main'
        run: bash build.sh --configuration=Debug
      
      - name: Execute build script (Release)
        id: build_release
        if: github.ref == 'refs/heads/main'
        run: bash build.sh --configuration=Release
      
      - name: Publish build artifact
        id: publish_artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: nbaproject.blazor-artifact
          path: ./release
      
      - name: Create release
        id: create_release
        if: github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_ID: v0.1.1
        with:
          tag_name: ${{ env.VERSION_ID }}
          release_name: ${{ env.VERSION_ID }}
          body: Release --- ${{ env.VERSION_ID }}
          draft: false
          prerelease: true
          allowUpdates: true

  deploy:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        id: download_artifacts
        uses: actions/download-artifact@v2
      
      - name: Publish to Azure AppService
        id: publish_to_azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: NBAProject-Blazor-App
          package: ./nbaproject.blazor-artifact
          publish-profile: ${{ secrets.AZURE_PUBLISH_SETTINGS }}